dependencies:
  - OpenZeppelin/openzeppelin-contracts@5.0.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@5.0.1'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  sepolia:
    verify: True
